name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.19']
    steps:
      -
        name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      -
        name: Checkout
        uses: actions/checkout@v3
#       run: go run main.go
