name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  go-lint:
    name: lint-${{ matrix.go_version }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['^1.21']
    steps:
      -
        name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          cache: true
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run golangci linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-go-installation: true
  go-test:
    name: test-${{ matrix.go_version }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['^1.21']
    steps:
      -
        name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          cache: true
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run golang unit tests
        run: |
          go test -short -coverprofile=build/coverage.txt -covermode=atomic ./...
